### ISSUE TITLE
Chests Wiping Inventory

### ISSUE THREAD

**Issue by zuad24** [BlueStaggo/MCDiverge#30] opened 2024-08-03 19:15 UTC
I doubt this is intentional, but it seems like if chunks are unloaded, chests will clear. This seemingly happens with player made chests as well as loot chests. Been quite frustrating.

Present as of 1.0-a9.2

**Comment by BlueStaggo** [comment] 2024-08-05 09:21
Don't rub it in. It'll hopefully get resolved somehow.

**Comment by BlueStaggo** [comment] 2024-09-10 19:56
Fixed in 1.0-a9.3, at least with a quick and dirty fix with disabling chunk unloading in singleplayer for the time being.

**Closed as completed by BlueStaggo** 2024-09-10 19:56 UTC
Labels: bug, beta rework

**Comment by BlueStaggo** [comment] 2024-09-11 12:12
Didn't notice it was a duplicate of #27
